"""add handler code and frontend callers

Revision ID: 377900b188c8
Revises: 
Create Date: 2026-06-08 17:04:48.170129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377900b188c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_routes', sa.Column('handler_code', sa.Text(), nullable=True))
    op.add_column('api_routes', sa.Column('frontend_callers', sa.JSON(), nullable=True))
    op.drop_column('dependencies', 'homepage')
    op.drop_column('dependencies', 'license')
    op.drop_column('dependencies', 'update_status')
    op.drop_column('dependencies', 'latest_version')
    op.drop_column('dependencies', 'license_ok')
    op.drop_column('dependencies', 'description')
    op.drop_column('repositories', 'watchers')
    op.drop_column('repositories', 'open_issues')
    op.drop_column('repositories', 'health_trend')
    op.drop_column('repositories', 'health_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('health_grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('health_trend', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('open_issues', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repositories', sa.Column('watchers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('license_ok', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('latest_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('update_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('license', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dependencies', sa.Column('homepage', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('api_routes', 'frontend_callers')
    op.drop_column('api_routes', 'handler_code')
    # ### end Alembic commands ###
